//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Istek = new HashSet<Istek>();
            this.KiralikAraclar = new HashSet<KiralikAraclar>();
        }
    
        public int aracID { get; set; }
        public Nullable<int> sirketID { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public Nullable<int> yasSiniri { get; set; }
        public Nullable<int> ehliyetYasi { get; set; }
        public Nullable<int> gunlukKm { get; set; }
        public Nullable<long> KM { get; set; }
        public Nullable<bool> airbag { get; set; }
        public Nullable<int> bagajHacmi { get; set; }
        public Nullable<int> koltukSayisi { get; set; }
        public Nullable<decimal> gunlukFiyat { get; set; }
    
        public virtual Sirket Sirket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Istek> Istek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiralikAraclar> KiralikAraclar { get; set; }
    }
}
