//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaDBEntities : DbContext
    {
        public AracKiralamaDBEntities()
            : base("name=AracKiralamaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arac> Arac { get; set; }
        public virtual DbSet<Istek> Istek { get; set; }
        public virtual DbSet<İl> İl { get; set; }
        public virtual DbSet<KiralikAraclar> KiralikAraclar { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<MusteriBilgileri> MusteriBilgileri { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
