//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralikAraclar
    {
        public int kiralikaraclarID { get; set; }
        public int musteriID { get; set; }
        public int aracID { get; set; }
        public Nullable<System.DateTime> baslangicTarihi { get; set; }
        public Nullable<System.DateTime> bitisTarihi { get; set; }
        public Nullable<decimal> kiralamaUcreti { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
