//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int kullaniciID { get; set; }
        public Nullable<int> sirketID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<int> rolID { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Sirket Sirket { get; set; }
    }
}
