//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriBilgileri
    {
        public int musteriID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public string telNo { get; set; }
        public Nullable<int> ilID { get; set; }
        public string acikAdres { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public Nullable<System.DateTime> ehliyetTarihi { get; set; }
    
        public virtual İl İl { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
